#!/bin/bash

# Set apache configurations
APACHE_DOCUMENT_ROOT=/var/www/public

sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf
sed -ri -e "s!/var/www/!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

sed -i "s/Listen 80/Listen ${PORT:-80}/g" /etc/apache2/ports.conf
sed -i "s/:80/:${PORT:-80}/g" /etc/apache2/sites-enabled/*

sed -i '/es_MX.UTF-8/s/^# //g' /etc/locale.gen
locale-gen

# Install composer dependencies
composer install

# Install node dependencies to build assets
npm install
npm run prod

# Laravel setup
chmod -R 777 storage/
chmod -R 777 bootstrap/cache
rm public/storage
php artisan storage:link

